# Generated by Django 3.2.19 on 2024-01-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('DOB', models.CharField(max_length=250)),
                ('Age', models.CharField(max_length=250)),
                ('Gender', models.CharField(max_length=250)),
                ('Phone', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Address', models.TextField(max_length=250)),
                ('District', models.CharField(max_length=250)),
                ('Branch', models.CharField(max_length=250)),
                ('Account_Type', models.CharField(max_length=250)),
                ('Materials_Provided', models.CharField(max_length=250)),
            ],
        ),
    ]
