# Generated by Django 3.2.19 on 2024-01-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdetails',
            old_name='name',
            new_name='Name',
        ),
    ]
