# Generated by Django 3.2.19 on 2024-01-12 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_rename_name_formdetails_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formdetails',
            table='formdetails',
        ),
    ]
