# Generated by Django 3.2.19 on 2024-01-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_auto_20240112_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appformdetails',
            new_name='formdetails',
        ),
        migrations.AlterModelTable(
            name='formdetails',
            table='formdetails',
        ),
    ]
